name: ping URL

inputs:
  url:
    description: URL to ping
    required: true
  max_trials:
    description: Maximum number of trial 
    default: '10'
    required: false
  delay:
    description: Delay in second between trial 
    default: '5'
    required: false 

runs:
  using: docker
  